### ISSUE TITLE
WAF not working

### ISSUE THREAD

**Issue by gsohler** [greenm01/poly2tri#119]
Stupid error, but cant proceed
I never heard from WAF before and i tried to follow the steps in the README

sohler@localhost poly2tri]$ ./waf configure
  set_options
Traceback (most recent call last):
  File "/home/gsohler/projects/3dprinter/poly2tri/.waf3-1.6.2-e067f3811b710f6de44f50177143d064/waflib/Node.py", line 272, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./waf", line 161, in <module>
    Scripting.waf_entry_point(cwd, VERSION, wafdir)
  File "/home/gsohler/projects/3dprinter/poly2tri/.waf3-1.6.2-e067f3811b710f6de44f50177143d064/waflib/Scripting.py", line 91, in waf_entry_point
    parse_options()
  File "/home/gsohler/projects/3dprinter/poly2tri/.waf3-1.6.2-e067f3811b710f6de44f50177143d064/waflib/Scripting.py", line 121, in parse_options
    opt=Options.OptionsContext().execute()
  File "/home/gsohler/projects/3dprinter/poly2tri/.waf3-1.6.2-e067f3811b710f6de44f50177143d064/waflib/Options.py", line 126, in execute
    super(OptionsContext,self).execute()
  File "/home/gsohler/projects/3dprinter/poly2tri/.waf3-1.6.2-e067f3811b710f6de44f50177143d064/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/gsohler/projects/3dprinter/poly2tri/.waf3-1.6.2-e067f3811b710f6de44f50177143d064/waflib/Context.py", line 127, in recurse
    user_function(self)
  File "/home/gsohler/projects/3dprinter/poly2tri/wscript", line 34, in options
    opt.load('compiler_cxx')
  File "/home/gsohler/projects/3dprinter/poly2tri/.waf3-1.6.2-e067f3811b710f6de44f50177143d064/waflib/Context.py", line 84, in load
    fun(self)
  File "/home/gsohler/projects/3dprinter/poly2tri/.waf3-1.6.2-e067f3811b710f6de44f50177143d064/waflib/Tools/compiler_cxx.py", line 31, in options
    opt.load_special_tools('cxx_*.py')
  File "/home/gsohler/projects/3dprinter/poly2tri/.waf3-1.6.2-e067f3811b710f6de44f50177143d064/waflib/Context.py", line 251, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/home/gsohler/projects/3dprinter/poly2tri/.waf3-1.6.2-e067f3811b710f6de44f50177143d064/waflib/Node.py", line 320, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=25,dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/gsohler/projects/3dprinter/poly2tri/.waf3-1.6.2-e067f3811b710f6de44f50177143d064/waflib/Node.py", line 320, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=25,dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration

whats going wrong in my place ?

**Comment by jszmwq** [comment]
I had the same problem in windows cmd.
D:\tools\poly2tri-master>python waf configure
  set_options
Traceback (most recent call last):
  File "D:\tools\poly2tri-master\waf3-1.6.2-e067f3811b710f6de44f50177143d064\waflib\Node.py", line 272, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\tools\poly2tri-master\waf", line 161, in <module>
    Scripting.waf_entry_point(cwd, VERSION, wafdir)
  File "D:\tools\poly2tri-master\waf3-1.6.2-e067f3811b710f6de44f50177143d064\waflib\Scripting.py", line 91, in waf_entry_point
    parse_options()
  File "D:\tools\poly2tri-master\waf3-1.6.2-e067f3811b710f6de44f50177143d064\waflib\Scripting.py", line 121, in parse_options
    opt=Options.OptionsContext().execute()
  File "D:\tools\poly2tri-master\waf3-1.6.2-e067f3811b710f6de44f50177143d064\waflib\Options.py", line 126, in execute
    super(OptionsContext,self).execute()
  File "D:\tools\poly2tri-master\waf3-1.6.2-e067f3811b710f6de44f50177143d064\waflib\Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "D:\tools\poly2tri-master\waf3-1.6.2-e067f3811b710f6de44f50177143d064\waflib\Context.py", line 127, in recurse
    user_function(self)
  File "D:\tools\poly2tri-master\wscript", line 34, in options
    opt.load('compiler_cxx')
  File "D:\tools\poly2tri-master\waf3-1.6.2-e067f3811b710f6de44f50177143d064\waflib\Context.py", line 84, in load
    fun(self)
  File "D:\tools\poly2tri-master\waf3-1.6.2-e067f3811b710f6de44f50177143d064\waflib\Tools\compiler_cxx.py", line 31, in options
    opt.load_special_tools('cxx_*.py')
  File "D:\tools\poly2tri-master\waf3-1.6.2-e067f3811b710f6de44f50177143d064\waflib\Context.py", line 251, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "D:\tools\poly2tri-master\waf3-1.6.2-e067f3811b710f6de44f50177143d064\waflib\Node.py", line 320, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=25,dir=dir,src=src,remove=kw.get('remove',True))]
  File "D:\tools\poly2tri-master\waf3-1.6.2-e067f3811b710f6de44f50177143d064\waflib\Node.py", line 320, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=25,dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
